# Generated by Django 4.1.5 on 2023-01-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosnsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosnsmodel',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosnsmodel',
            name='read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosnsmodel',
            name='readtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
