# Generated by Django 4.1.5 on 2023-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosnsApp', '0002_alter_cosnsmodel_good_alter_cosnsmodel_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosnsmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cosnsmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cosnsmodel',
            name='readtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
